// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlNplxHZ37YQRaso030SJyI0_KeVeEfp8',
    appId: '1:264492426413:web:3ca3ec435c1c68729e1224',
    messagingSenderId: '264492426413',
    projectId: 'projeni-bul-app',
    authDomain: 'projeni-bul-app.firebaseapp.com',
    storageBucket: 'projeni-bul-app.appspot.com',
    measurementId: 'G-955QSYFRC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSSme0mA45dhuqPCnvCDs90zf8M7SWvIM',
    appId: '1:264492426413:android:bc0e175ef78c6d809e1224',
    messagingSenderId: '264492426413',
    projectId: 'projeni-bul-app',
    storageBucket: 'projeni-bul-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnxmkabY0S_EfY3VIQJ7Doikmo9LsxT5o',
    appId: '1:264492426413:ios:b07a2e950b15d4d59e1224',
    messagingSenderId: '264492426413',
    projectId: 'projeni-bul-app',
    storageBucket: 'projeni-bul-app.appspot.com',
    iosClientId: '264492426413-5guve6cbvt93puhb7lcktt6i7tp94nu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.jamArchitecture',
  );
}
